#!/usr/bin/env bash
# Challenge-track asset locations only; per-map configs are generated by the launcher.
LMM_SUBMISSION_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export LMM_SUBMISSION_ROOT
export LMM_MODEL_ROOT="${MODEL_ROOT:-$LMM_SUBMISSION_ROOT/models}"
export MODERNBERT_MODEL_PATH="$LMM_MODEL_ROOT/modernbert-drive-command-compositional"
export VLA_MODEL_PATH="$LMM_MODEL_ROOT/lightweight_vla_adapter/universal_three_scene_v6_sensor_policy/model.pt"
# Do not inherit a legacy base-track configuration from the caller.
unset VLA_CONFIG_PATH
printf 'Challenge runtime config is generated per scene by experiment/CARLA/tools/run_challenge_x86.py\n'
